import {
  Fuel,
  Plane,
  Building,
  Phone,
  Utensils,
  Car,
  Briefcase,
  FileText,
  Ship,
  Ticket,
  Wrench,
  Mail,
  Users,
  Info,
  Hotel,
  CarTaxiFront,
  Video,
} from 'lucide-react'
import React, { type ElementType } from 'react'

export const categoryIcons: { [key: string]: ElementType } = {
  'COMBUSTÍVEIS E LUBRIFICANTES.': Fuel,
  'PASSAGENS AÉREAS': Plane,
  'MANUTENÇÃO DE ESCRITÓRIO': Building,
  'DIVULGAÇÃO DA ATIVIDADE PARLAMENTAR.': Video,
  TELEFONIA: Phone,
  HOSPEDAGEM: Hotel,
  'FORNECIMENTO DE ALIMENTAÇÃO DO PARLAMENTAR': Utensils,
  'LOCAÇÃO DE VEÍCULOS AUTOMOTORES': CarTaxiFront,
  'LOCAÇÃO OU FRETAMENTO DE VEÍCULOS AUTOMOTORES': CarTaxiFront,
  'LOCAÇÃO OU FRETAMENTO DE AERONAVES': Plane,
  'CONSULTORIAS, PESQUISAS E TRABALHOS TÉCNICOS.': Briefcase,
  'SERVIÇOS POSTAIS': Mail,
  'ASSINATURA DE PUBLICAÇÕES': FileText,
  'LOCAÇÃO DE EMBARCAÇÃO': Ship,
  'PASSAGENS TERRESTRES, MARÍTIMAS OU FLUVIAIS': Ticket,
  'SERVIÇO DE TÁXI, PEDÁGIO E ESTACIONAMENTO': Car,
  'SERVIÇOS DE SEGURANÇA PRIVADA': Users,
  'PARTICIPAÇÃO EM CURSO, PALESTRA OU EVENTO SIMILAR': Info,
  ' fretamento de aeronaves': Plane,
  ' fretamento de veículos automotores': CarTaxiFront,
  ' locação ou fretamento de embarcações': Ship,
  ' locação ou fretamento de veículos automotores': CarTaxiFront,
  'SERVIÇO DE TÁXI, PEDÁGIO E ESTACIONAMENTO.': Car,
  'DIVULGAÇÃO DA ATIVIDADE PARLAMENTAR': Video,
  'PASSAGEM AÉREA': Plane,
  'PASSAGEM AÉREA - SIGEPA': Plane,
  'COMBUSTÍVEIS E LUBRIFICANTES': Fuel,
  'CONSULTORIAS, PESQUISAS E TRABALHOS TÉCNICOS': Briefcase,
  'LOCAÇÃO DE VEÍCULOS AUTOMOTORES OU FRETAMENTO DE EMBARCAÇÕES': CarTaxiFront,
  'MANUTENÇÃO DE ESCRITÓRIO DE APOIO À ATIVIDADE PARLAMENTAR': Building,
  'SERVIÇOS POSTAIS.': Mail,
  'ASSINATURA DE PUBLICAÇÕES.': FileText,
  'FORNECIMENTO DE ALIMENTAÇÃO DO PARLAMENTAR.': Utensils,
  'HOSPEDAGEM.': Hotel,
  'LOCAÇÃO DE VEÍCULO AUTOMOTOR OU FRETAMENTO DE EMBARCAÇÃO.': CarTaxiFront,
  'SERVIÇO DE TÁXI, PEDÁGIO E ESTACIONAMENTO ': Car,
  'SERVIÇOS DE SEGURANÇA PRIVADA.': Users,
  'TELEFONIA.': Phone,
  'AQUISIÇÃO DE MATERIAL DE ESCRITÓRIO.': Wrench,
  'AQUISIÇÃO OU LOC. DE SOFTWARE; SERV. POSTAIS; ASS. PUBLICAÇÕES': FileText,
  'COMBUSTÍVEIS E LUBRIFICANTES ': Fuel,
  'DIVULGAÇÃO DA ATIVIDADE PARLAMENTAR ': Video,
  'EMISSÃO BILHETE AÉREO': Ticket,
  'FORNECIMENTO DE ALIMENTAÇÃO DO PARLAMENTAR ': Utensils,
  'LOCAÇÃO DE VEÍCULOS AUTOMOTORES.': CarTaxiFront,
  'MANUTENÇÃO DE ESCRITÓRIO DE APOIO À ATIVIDADE PARLAMENTAR.': Building,
  'PASSAGEM AÉREA - REEMBOLSO': Plane,
  'SERVIÇO DE TÁXI, PEDÁGIO E ESTACIONAMENTO. ': Car,
  'SERVIÇOS DE PROVIMENTO DE INTERNET': Info,
  'SERVIÇOS GRÁFICOS': FileText,
  'PASSAGENS TERRESTRES, MARÍTIMAS OU FLUVIAIS.': Ticket,
  'PARTICIPAÇÃO EM CURSO, PALESTRA OU EVENTO SIMILAR.': Info,
  'LOCAÇÃO DE VEÍCULO AUTOMOTOR': CarTaxiFront,
  'PASSAGEM AÉREA - COTA': Plane,
  'PASSAGEM AÉREA - PAGAMENTO DIRETO': Plane,
  'AQUISIÇÃO DE MATERIAIS DE ESCRITÓRIO': Wrench,
  'Contratação de consultorias, assessorias, pesquisas, trabalhos técnicos e outros serviços de apoio ao exercício do mandato parlamentar': Briefcase,
  'Divulgação da atividade parlamentar': Video,
  'Locação de meios de transporte': CarTaxiFront,
  'passagens aéreas': Plane,
  'Gastos com combustíveis e lubrificantes': Fuel,
  'Serviços de postagem': Mail,
  'Alimentação': Utensils,
  'Hospedagem, exceto do parlamentar no distrito federal': Hotel,
  'Serviços de comunicação': Phone,
  'Serviços de segurança': Users,
  'Despesas com locomoção, contemplando': Car,
  'Manutenção de escritórios de apoio à atividade parlamentar': Building,
  'Aquisição de material de consumo para uso no escritório': Wrench,
  'Aquisição ou aluguel de licenças de software': FileText,
  'Outras despesas com locomoção': Car,
  'Outros serviços de apoio ao mandato parlamentar': Briefcase,
  'Táxi, pedágio e estacionamento': Car,
  'Aluguel de veículos': CarTaxiFront,
  'Passagens e despesas com locomoção': Ticket,
  'Combustíveis e lubrificantes': Fuel,
  'Material de expediente': Wrench,
  'Serviços gráficos e de encadernação': FileText,
  'Consultoria': Briefcase,
  'Aluguel de imóveis para escritório político': Building,
  'Divulgação de atividade parlamentar': Video,
  'Serviços de telecomunicações': Phone,
  'Despesas com pessoal': Users,
  'Aquisição de equipamentos e materiais permanentes': Wrench,
  'Serviços contratados': Briefcase,
  'Viagens e hospedagem': Hotel,
  'Correios': Mail,
  'Transporte, hospedagem e alimentação': Hotel,
  'Material de escritório': Wrench,
  'Comunicações': Phone,
  'Serviços de terceiros': Briefcase,
  'Transporte': Car,
  'Alimentação ': Utensils,
  'Divulgação': Video,
  'Material de consumo': Wrench,
  'Passagens': Ticket,
  'Serviços de informação e comunicação': Phone,
  'Serviços de consultoria': Briefcase,
  'Transportes': Car,
  'Hospedagem e alimentação': Hotel,
  'Serviços de publicidade': Video,
  'Serviços de correspondência': Mail,
  'Serviços de telecomunicação': Phone,
  'Serviços de processamento de dados': Info,
  'Serviços de locação de veículos': CarTaxiFront,
  'Serviços de manutenção e conservação': Building,
  'Serviços de segurança ': Users,
  'Serviços de transporte e hospedagem': Hotel,
  'Serviços técnicos profissionais': Briefcase,
  'Combustível': Fuel,
  'Aluguel de veículos automotores': CarTaxiFront,
  'Divulgação do mandato parlamentar': Video,
  'Passagens aéreas, terrestres e fluviais': Ticket,
  'Manutenção de gabinete': Building,
  'Despesas com transporte, alimentação e hospedagem': Hotel,
  'Serviços de comunicação e informática': Phone,
  'Serviços de consultoria e assessoria': Briefcase,
  'Serviços de segurança.': Users,
  'Despesas com divulgação da atividade parlamentar': Video,
  'Despesas com combustíveis e lubrificantes': Fuel,
  'Despesas com locação de veículos': CarTaxiFront,
  'Despesas com passagens aéreas': Plane,
  'Despesas com serviços de comunicação': Phone,
  'Despesas com serviços de consultoria': Briefcase,
  'Despesas com serviços de segurança': Users,
  'Despesas com hospedagem': Hotel,
  'Despesas com alimentação': Utensils,
  'Despesas com transporte': Car,
  'Despesas com material de escritório': Wrench,
  'Despesas com serviços gráficos': FileText,
  'Despesas com correios': Mail,
  'Despesas com outras despesas': Briefcase,
  'Despesas com pessoal.': Users,
  'Despesas com viagens': Hotel,
  'Despesas com publicidade': Video,
  'Despesas com aluguel de imóveis': Building,
  'Despesas com aluguel de veículos': CarTaxiFront,
  'Despesas com passagens': Ticket,
  'Despesas com combustíveis': Fuel,
  'Despesas com serviços de terceiros': Briefcase,
  'Despesas com material de consumo': Wrench,
  'Despesas com comunicações': Phone,
  'Despesas com transporte e hospedagem': Hotel,
  'Despesas com serviços de informação e comunicação': Phone,
  'Despesas com serviços de consultoria e assessoria.': Briefcase,
  'Despesas com serviços de segurança privada': Users,
  'Despesas com serviços de transporte e hospedagem.': Hotel,
  'Despesas com serviços técnicos profissionais.': Briefcase,
  'Despesas com combustível.': Fuel,
  'Despesas com aluguel de veículos automotores.': CarTaxiFront,
  'Despesas com divulgação do mandato parlamentar.': Video,
  'Despesas com passagens aéreas, terrestres e fluviais.': Ticket,
  'Despesas com manutenção de gabinete.': Building,
  'Despesas com transporte, alimentação e hospedagem.': Hotel,
  'Despesas com serviços de comunicação e informática.': Phone,
}
